import os
from datetime import datetime
from asammdf import MDF
import tkinter as tk
from tkinter import filedialog


def select_files(root):
    """Use existing root instead of creating a new Tk instance."""
    return filedialog.askopenfilenames(
        parent=root,
        title="Select MF4 files",
        filetypes=[("MDF files", "*.mf4 *.mdf")]
    )


def write_trc(mdf_file):
    print(f"\nProcessing: {os.path.basename(mdf_file)}")
    mdf = MDF(mdf_file)

    records = []

    # Extract CAN frames from all groups
    for group_index, group in enumerate(mdf.groups):
        try:
            timestamps = mdf.get("Timestamp", group=group_index).samples
            ids = mdf.get("CAN_DataFrame.ID", group=group_index).samples
            data_bytes = mdf.get("CAN_DataFrame.DataBytes", group=group_index).samples
            dlc = mdf.get("CAN_DataFrame.DataLength", group=group_index).samples
            direction = mdf.get("CAN_DataFrame.Dir", group=group_index).samples
        except Exception:
            continue

        for ts, frame_id, data, length, dir_flag in zip(
                timestamps, ids, data_bytes, dlc, direction):

            frame_id = int(frame_id)
            raw_bytes = bytes(data)[:int(length)]
            length = int(length)

            # Convert time to ms offset
            time_ms = float(ts) * 1000.0

            # Determine direction
            msg_type = "Rx" if int(dir_flag) == 0 else "Tx"

            records.append((time_ms, msg_type, frame_id, length, raw_bytes))

    if not records:
        print("No CAN frames found.")
        return

    # Sort by timestamp
    records.sort(key=lambda x: x[0])

    output_file = os.path.splitext(mdf_file)[0] + ".trc"

    with open(output_file, "w") as f:

        # PCAN-style header
        f.write(";$FILEVERSION=1.1\n")
        f.write(";$STARTTIME=0\n")
        f.write(";\n")
        f.write(";   Generated by Python MDF to TRC Converter\n")
        f.write(";\n")
        f.write(";   Message Number\n")
        f.write(";   |         Time Offset (ms)\n")
        f.write(";   |         |        Type\n")
        f.write(";   |         |        |        ID (hex)\n")
        f.write(";   |         |        |        |     Data Length\n")
        f.write(";   |         |        |        |     |   Data Bytes (hex) ...\n")
        f.write(";   |         |        |        |     |   |\n")
        f.write(";---+--   ----+----  --+--  ----+---  +  -+ -- -- -- -- -- -- --\n")

        for i, (time_ms, msg_type, frame_id, length, raw_bytes) in enumerate(records, start=1):
            data_str = " ".join(f"{b:02X}" for b in raw_bytes)

            f.write(
                f"{i:6d})"
                f"{time_ms:12.1f}  "
                f"{msg_type:<2}  "
                f"{frame_id:8X}  "
                f"{length:1d}  "
                f"{data_str}\n"
            )

    print(f"Created: {output_file}")


def main(root):
    """Called from main TRC tool."""
    files = select_files(root)
    if not files:
        print("No files selected.")
        return

    for file in files:
        write_trc(file)

    print("\n✅ All TRC files created successfully.")


# Allow standalone execution
if __name__ == "__main__":
    root = tk.Tk()
    root.withdraw()
    main(root)
